In [1]:
from pathlib import Path

RAW_DATA = Path("../data/raw")

print("Raw data location:", RAW_DATA.resolve())
print("\nFiles found:")

for file in RAW_DATA.iterdir():
    print(file.name)

Raw data location: C:\Users\sathe\OneDrive\Desktop\AGGP\Projects\FleetPulse\data\raw

Files found:
N-CMAPSS_DS01-005.h5
N-CMAPSS_DS02-006.h5
N-CMAPSS_DS03-012.h5
N-CMAPSS_DS04.h5
N-CMAPSS_DS05.h5
N-CMAPSS_DS06.h5
N-CMAPSS_DS07.h5
N-CMAPSS_DS08a-009.h5
N-CMAPSS_DS08c-008.h5
N-CMAPSS_DS08d-010.h5
N-CMAPSS_Example_data_loading_and_exploration.ipynb
Run_to_Failure_Simulation_Under_Real_Flight_Conditions_Dataset.pdf


In [3]:
import h5py

file_path = RAW_DATA / "N-CMAPSS_DS01-005.h5"

with h5py.File(file_path, "r") as f:
    print("Top-level contents:")
    for key in f.keys():
        print("-", key)

Top-level contents:
- A_dev
- A_test
- A_var
- T_dev
- T_test
- T_var
- W_dev
- W_test
- W_var
- X_s_dev
- X_s_test
- X_s_var
- X_v_dev
- X_v_test
- X_v_var
- Y_dev
- Y_test


In [4]:
with h5py.File(file_path, "r") as f:
    print("Dataset shapes:\n")

    for key in f.keys():
        print(f"{key:10} -> {f[key].shape}")

Dataset shapes:

A_dev      -> (4906636, 4)
A_test     -> (2735232, 4)
A_var      -> (4,)
T_dev      -> (4906636, 10)
T_test     -> (2735232, 10)
T_var      -> (10,)
W_dev      -> (4906636, 4)
W_test     -> (2735232, 4)
W_var      -> (4,)
X_s_dev    -> (4906636, 14)
X_s_test   -> (2735232, 14)
X_s_var    -> (14,)
X_v_dev    -> (4906636, 14)
X_v_test   -> (2735232, 14)
X_v_var    -> (14,)
Y_dev      -> (4906636, 1)
Y_test     -> (2735232, 1)


In [5]:
with h5py.File(file_path, "r") as f:
    for key in ["A_var", "T_var", "W_var", "X_s_var", "X_v_var"]:
        print(f"\n--- {key} ---")
        print(f[key][:])


--- A_var ---
[b'unit' b'cycle' b'Fc' b'hs']

--- T_var ---
[b'fan_eff_mod' b'fan_flow_mod' b'LPC_eff_mod' b'LPC_flow_mod'
 b'HPC_eff_mod' b'HPC_flow_mod' b'HPT_eff_mod' b'HPT_flow_mod'
 b'LPT_eff_mod' b'LPT_flow_mod']

--- W_var ---
[b'alt' b'Mach' b'TRA' b'T2']

--- X_s_var ---
[b'T24' b'T30' b'T48' b'T50' b'P15' b'P2' b'P21' b'P24' b'Ps30' b'P40'
 b'P50' b'Nf' b'Nc' b'Wf']

--- X_v_var ---
[b'T40' b'P30' b'P45' b'W21' b'W22' b'W25' b'W31' b'W32' b'W48' b'W50'
 b'SmFan' b'SmLPC' b'SmHPC' b'phi']


In [6]:
with h5py.File(file_path, "r") as f:
    print("Y_dev first 20 values:")
    print(f["Y_dev"][:20])

    print("\nY_test first 20 values:")
    print(f["Y_test"][:20])

Y_dev first 20 values:
[[99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]
 [99]]

Y_test first 20 values:
[[89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]
 [89]]


In [7]:
import numpy as np

with h5py.File(file_path, "r") as f:
    y_dev = f["Y_dev"][:].flatten()
    y_test = f["Y_test"][:].flatten()

print("Y_dev")
print("Minimum:", y_dev.min())
print("Maximum:", y_dev.max())
print("Unique values:", np.unique(y_dev)[:30])
print("Number of unique values:", len(np.unique(y_dev)))

print("\nY_test")
print("Minimum:", y_test.min())
print("Maximum:", y_test.max())
print("Unique values:", np.unique(y_test)[:30])
print("Number of unique values:", len(np.unique(y_test)))

Y_dev
Minimum: 0
Maximum: 99
Unique values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Number of unique values: 100

Y_test
Minimum: 0
Maximum: 89
Unique values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Number of unique values: 90


In [8]:
with h5py.File(file_path, "r") as f:
    A_dev = f["A_dev"][:]

print("First 20 rows of A_dev:")
print(A_dev[:20])

print("\nNumber of unique engines:", len(np.unique(A_dev[:, 0])))

print("\nFirst 20 engine IDs:")
print(np.unique(A_dev[:, 0])[:20])

First 20 rows of A_dev:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Number of unique engines: 6

First 20 engine IDs:
[1. 2. 3. 4. 5. 6.]


In [9]:
with h5py.File(file_path, "r") as f:
    A_dev = f["A_dev"][:]
    Y_dev = f["Y_dev"][:].flatten()

engine_1 = A_dev[:, 0] == 1

engine_1_data = A_dev[engine_1]
engine_1_y = Y_dev[engine_1]

print("Engine 1 rows:", len(engine_1_data))
print("First 10 cycles:", engine_1_data[:10, 1])
print("Last 10 cycles:", engine_1_data[-10:, 1])

print("\nFirst 10 Y values:", engine_1_y[:10])
print("Last 10 Y values:", engine_1_y[-10:])

print("\nEngine 1 final cycle:", engine_1_data[-1, 1])
print("Engine 1 final Y:", engine_1_y[-1])

Engine 1 rows: 433325
First 10 cycles: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Last 10 cycles: [100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]

First 10 Y values: [99 99 99 99 99 99 99 99 99 99]
Last 10 Y values: [0 0 0 0 0 0 0 0 0 0]

Engine 1 final cycle: 100.0
Engine 1 final Y: 0


In [10]:
with h5py.File(file_path, "r") as f:
    A_dev = f["A_dev"][:]
    W_dev = f["W_dev"][:]
    X_s_dev = f["X_s_dev"][:]
    X_v_dev = f["X_v_dev"][:]
    Y_dev = f["Y_dev"][:].flatten()

mask = (A_dev[:, 0] == 1) & (A_dev[:, 1] == 1)

print("Rows in Engine 1, Cycle 1:", mask.sum())

print("\nA values:")
print(A_dev[mask][:5])

print("\nW values:")
print(W_dev[mask][:5])

print("\nX_s values:")
print(X_s_dev[mask][:5])

print("\nX_v values:")
print(X_v_dev[mask][:5])

print("\nY values:")
print(Y_dev[mask][:20])

Rows in Engine 1, Cycle 1: 4498

A values:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

W values:
[[3.01300000e+03 3.76361996e-01 7.03119965e+01 5.22314770e+02]
 [3.02000000e+03 3.76865983e-01 7.03119965e+01 5.22327145e+02]
 [3.02500000e+03 3.77685010e-01 7.03119965e+01 5.22371840e+02]
 [3.03500000e+03 3.76991987e-01 7.03998871e+01 5.22282418e+02]
 [3.04300000e+03 3.77622008e-01 7.03998871e+01 5.22300605e+02]]

X_s values:
[[6.18288596e+02 1.47046980e+03 1.84962068e+03 1.26927559e+03
  1.94320701e+01 1.44846114e+01 1.97279900e+01 2.44109904e+01
  3.94701872e+02 4.01205188e+02 1.59747711e+01 2.14225346e+03
  8.69317650e+03 4.62162177e+00]
 [6.18296355e+02 1.47041559e+03 1.84951987e+03 1.26917716e+03
  1.94313853e+01 1.44846828e+01 1.97272947e+01 2.44104827e+01
  3.94629899e+02 4.01132851e+02 1.59705181e+01 2.14221860e+03
  8.69300030e+03 4.62056103e+00]
 [6.18336514e+02 1.47045385e+03 1.84956614e+03 1.26916735e+03
  1.94351626e+01 1.44882235e+01 1.9731129

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [8]:
import src.data_loader as dl

print(dl.__file__)
print(dir(dl))

c:\Users\sathe\OneDrive\Desktop\AGGP\Projects\FleetPulse\src\data_loader.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']


In [9]:
import importlib
import src.data_loader as dl

importlib.reload(dl)

print(dl.__file__)
print("load_dataset" in dir(dl))

c:\Users\sathe\OneDrive\Desktop\AGGP\Projects\FleetPulse\src\data_loader.py
True


In [10]:
data = dl.load_dataset("N-CMAPSS_DS01-005.h5")

print(data.keys())

dict_keys(['A', 'T', 'W', 'X_s', 'X_v', 'Y'])


In [11]:
for name, values in data.items():
    print(f"{name}: {values.shape}")

A: (4906636, 4)
T: (4906636, 10)
W: (4906636, 4)
X_s: (4906636, 14)
X_v: (4906636, 14)
Y: (4906636, 1)


In [6]:
import importlib
import src.data_loader as dl

importlib.reload(dl)

print(dl.A_COLUMNS)
print(dl.W_COLUMNS)
print(dl.X_S_COLUMNS)

['unit', 'cycle', 'Fc', 'hs']
['alt', 'Mach', 'TRA', 'T2']
['T24', 'T30', 'T48', 'T50', 'P15', 'P2', 'P21', 'P24', 'Ps30', 'P40', 'P50', 'Nf', 'Nc', 'Wf']


In [5]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))